run:
  scraper: cnyes
  # n_batch: 50
  n_workers: 1
  loop_every: null  # in seconds

store:
  es:
    host: 'es:9200'
  db:
    # driver: postgresql
    user: sqlpad
    password: sqlpad
    host: pg
    dbname: test
  # csv:
  #   # path: ./resource/rss.csv
  #   path: ./rss/resource/rss.csv

scraper:
  rss:
    entry: './resource/rss_yahoo_us.csv'  # path for startpoints
    fetch_rss_every_n_seconds: 604800  # hold maximum 7 days for refetch
    force_fetch: false  # ignore sleep time
  cnbc:
    store: es
  cnyes_api: 
    start: [2020, 5, 5]  # [year, month, day]
    # until: [2010, 3, 1]  # [year, month, day]
    until: null # [year, month, day]

proxy:
  enabled: true
  path: ./proxies.txt
  

    


