db:
  # driver: postgresql
  user: sqlpad
  password: sqlpad
  host: pg
  dbname: test
csv:
  # path: ./resource/rss.csv
  path: ./rss/resource/rss.csv
scrape:
  fetch_rss_every_n_seconds: 172800  # hold maximum 2 days for refetch
